update public."Category" set color='#455a64' where name='Groceries';
update public."Category" set color='#d32f2f' where name='Vegetables, Fruits, Dairy and Meat';
update public."Category" set color='#c2185b' where name='Rent and Other Bills';
update public."Category" set color='#7b1fa2' where name='Transport';
update public."Category" set color='#512da8' where name='Fuel';
update public."Category" set color='#303f9f' where name='Medical and Pharmacy Bill';
update public."Category" set color='#1976d2' where name='Outside Food';
update public."Category" set color='#0288d1' where name='Shopping';
update public."Category" set color='#0097a7' where name='Entertainment';
update public."Category" set color='#00796b' where name='Salon and Beauty Products';
update public."Category" set color='#388e3c' where name='Gift';
update public."Category" set color='#689f38' where name='Holidays';
update public."Category" set color='#afb42b' where name='Investments';
update public."Category" set color='#fbc02d' where name='Gaming';
update public."Category" set color='#ffa000' where name='Kids';
update public."Category" set color='#f57c00' where name='Repair';
update public."Category" set color='#80C783' where name='Sport';
update public."Category" set color='#512DA7' where name='Home';
update public."Category" set color='#C2175B' where name='Work';
update public."Category" set color='#F44236' where name='Transfer';
update public."Category" set color='#E57373' where name='Others';