update public."Category" set falls_under='Food' where name='Groceries';
update public."Category" set falls_under='Food' where name='Vegetables, Fruits, Dairy and Meat';
update public."Category" set falls_under='Residence' where name='Rent and Other Bills';
update public."Category" set falls_under='Workplace' where name='Transport';
update public."Category" set falls_under='Workplace' where name='Fuel';
update public."Category" set falls_under='Medical' where name='Medical and Pharmacy Bill';
update public."Category" set falls_under='Food' where name='Outside Food';
update public."Category" set falls_under='Clothing and Accessories' where name='Shopping';
update public."Category" set falls_under='Pleasure and others' where name='Entertainment';
update public."Category" set falls_under='Clothing and Accessories' where name='Salon and Beauty Products';
update public."Category" set falls_under='Pleasure and others' where name='Gift';
update public."Category" set falls_under='Pleasure and others' where name='Holidays';
update public."Category" set falls_under='Residence' where name='Investments';
update public."Category" set falls_under='Pleasure and others' where name='Gaming';
update public."Category" set falls_under='Workplace' where name='Kids';
update public."Category" set falls_under='Residence' where name='Repair';
update public."Category" set falls_under='Pleasure and others' where name='Sport';
update public."Category" set falls_under='Residence' where name='Home';
update public."Category" set falls_under='Workplace' where name='Work';
update public."Category" set falls_under='Pleasure and others' where name='Transfer';
update public."Category" set falls_under='Pleasure and others' where name='Others';